[source]
working_dir = "./"
reflect_temporary_file = false
reflect_delete = false
pending_delete_time = ""
path_list = [""]

[target]
target_ip = ""
target_user = ""
target_password = ""
target_working_dir = ""